# Generated by Django 4.2.11 on 2026-05-18 04:57

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enlisted_email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=20, validators=[accounts.models.phone_number_validator])),
                ('business_name', models.CharField(blank=True, max_length=250, null=True)),
                ('problem_statement', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_attachment/')),
                ('status', models.CharField(blank=True, choices=[('', '--SELECT--'), ('pending', 'Pending'), ('on_progress', 'On Project'), ('solved', 'Solved')], max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
