# Generated by Django 4.2.11 on 2026-05-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='status',
            field=models.CharField(choices=[('', '--SELECT--'), ('pending', 'Pending'), ('on_progress', 'On Project'), ('solved', 'Solved')], default='pending', max_length=20),
        ),
    ]
