# Generated by Django 4.2.11 on 2026-05-19 06:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_alter_support_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetItNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=20, validators=[accounts.models.phone_number_validator])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='support',
            name='status',
            field=models.CharField(choices=[('', '--SELECT--'), ('pending', 'Pending'), ('on_progress', 'On Progress'), ('solved', 'Solved')], default='pending', max_length=20),
        ),
    ]
