# Generated by Django 4.2.11 on 2026-05-19 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_app', '0003_getitnow_alter_support_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='getitnow',
            name='contacted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_it_now_contacted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='getitnow',
            name='is_contacted',
            field=models.BooleanField(default=False),
        ),
    ]
