# Generated by Django 4.2.11 on 2026-05-19 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_getitnow_contacted_by_getitnow_is_contacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='getitnow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='getitnow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
