# Generated by Django 4.2.11 on 2026-05-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0005_getitnow_created_at_getitnow_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='support_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
