# Generated by Django 4.2.11 on 2026-05-20 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_alter_support_status'),
        ('dashboard_app', '0006_support_support_id'),
    ]

    operations = [
    ]
