# Generated by Django 4.2.11 on 2026-05-20 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_app', '0007_merge_20260520_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='support_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supported_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='support',
            name='status',
            field=models.CharField(choices=[('', '--SELECT--'), ('pending', 'Pending'), ('on_progress', 'On Progress'), ('solved', 'Solved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='support',
            name='support_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
