# Generated by Django 4.2.11 on 2026-08-05 04:59

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0008_support_support_by_alter_support_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[accounts.models.phone_number_validator]),
        ),
        migrations.AlterField(
            model_name='support',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
